-- This migration has been superseded by defining indexes directly in the Drizzle schema files.
-- The logic is now part of the migrations generated by `drizzle-kit`.

-- This migration adds indexes to foreign key columns that are frequently used in WHERE clauses,
-- especially for fetching user-specific data. This is a crucial step for overall application performance.

-- User settings and profile-related tables
CREATE INDEX IF NOT EXISTS idx_user_categories_profile_id ON public.user_categories (profile_id);
CREATE INDEX IF NOT EXISTS idx_user_subcodes_profile_id ON public.user_subcodes (profile_id);
CREATE INDEX IF NOT EXISTS idx_user_default_code_preferences_profile_id ON public.user_default_code_preferences (profile_id);
CREATE INDEX IF NOT EXISTS idx_shared_links_profile_id ON public.shared_links (profile_id);
CREATE INDEX IF NOT EXISTS idx_stats_cache_profile_id ON public.stats_cache (profile_id);

-- Messaging system
CREATE INDEX IF NOT EXISTS idx_conversations_participant1_id ON public.conversations (participant1_id);
CREATE INDEX IF NOT EXISTS idx_conversations_participant2_id ON public.conversations (participant2_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON public.messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON public.messages (sender_id);

-- Community features
CREATE INDEX IF NOT EXISTS idx_community_posts_profile_id ON public.community_posts (profile_id);
CREATE INDEX IF NOT EXISTS idx_community_comments_profile_id ON public.community_comments (profile_id);
CREATE INDEX IF NOT EXISTS idx_community_comments_post_id ON public.community_comments (post_id);

-- Notifications
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_id ON public.notifications (recipient_id);
CREATE INDEX IF NOT EXISTS idx_notifications_actor_id ON public.notifications (actor_id);

-- Planning features
CREATE INDEX IF NOT EXISTS idx_weekly_tasks_profile_id ON public.weekly_tasks (profile_id);
CREATE INDEX IF NOT EXISTS idx_weekly_notes_profile_id ON public.weekly_notes (profile_id);
CREATE INDEX IF NOT EXISTS idx_monthly_goals_profile_id ON public.monthly_goals (profile_id);
CREATE INDEX IF NOT EXISTS idx_monthly_reflections_profile_id ON public.monthly_reflections (profile_id);

-- Social features
CREATE INDEX IF NOT EXISTS idx_follows_follower_id ON public.follows (follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_following_id ON public.follows (following_id);

-- Memos
CREATE INDEX IF NOT EXISTS idx_memos_profile_id ON public.memos (profile_id);
CREATE INDEX IF NOT EXISTS idx_memos_record_id ON public.memos (record_id); 