// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

type Module = typeof import("../welcome-page.js")

type Info = GetInfo<{
  file: "features/users/pages/welcome-page.tsx",
  module: Module
}>